name: Build DLGMemor

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 使用 theos-action 自动配置环境
      - name: Setup Theos
        uses: Randomblock1/theos-action@v1

      # 执行编译命令
      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1

      # 收集生成的 deb 包
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DLGMemor-Package
          path: packages/*.deb
